<a href="https://colab.research.google.com/github/GulaiRandang/Data-Science_IF405_2026/blob/main/Pertemuan2_%5BAbdurrhman_AL_Asykari%5D_%5B240401010131%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Membuat list
data = [10, 20, 'Python', True, 3.14]

# Akses & slicing
print(data[0]) # → 10
print(data[-1]) # → 3.14 (dari belakang)
print(data[1:3]) # → [20, 'Python']

# Manipulasi
data.append(99) # tambah di akhir
data.insert(1, 55) # sisipkan di posisi 1
data.remove(20) # hapus nilai pertama = 20

# Urutkan (jika tipe sama)
data_angka = [10, 55, 3.14, 99]
data_angka.sort()
print(data_angka) # → [3.14, 10, 55, 99]

10
3.14
[20, 'Python']
[3.14, 10, 55, 99]


In [15]:
mahasiswa = {
'nama': 'Abdurrahman Al Asykari',
'nim': '240401010131',
'prodi': 'Informatika',
'ipk': 3.85
}
# Akses nilai
print(mahasiswa['nama']) # → 'Abdurrahman Al Asykari'
print(mahasiswa.get('usia', 0)) # default jika key tak ada
# Update dan hapus
mahasiswa['angkatan'] = 2024 # tambah key baru
del mahasiswa['nim'] # hapus key

Abdurrahman Al Asykari
0


In [19]:
import numpy as np
# Dari list Python
a1D = np.array([1, 2, 3, 4, 5]) # 1D
a2D = np.array([[1,2,3],[4,5,6]]) # 2D

# Array dengan nilai inisial
zeros = np.zeros((3, 4)) # nol semua
ones = np.ones((2, 3)) # satu semua
eye = np.eye(4) # matriks identitas
full = np.full((2, 2), 7) # nilai konstan

# Sequence
arange = np.arange(0, 20, 2) # 0,2,4,...18
linsp = np.linspace(0, 1, 11) # 11 titik merata

# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(100,))

In [21]:
# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b) # → [11 22 33 44 55]
print(a * b) # → [10 40 90 160 250]
print(a ** 2) # → [1 4 9 16 25]

# Universal functions (ufuncs)
np.sqrt(a) # akar kuadrat tiap elemen
np.exp(a) # eksponensial (e^x)
np.log(b) # logaritma natural

# Fungsi statistik
data = rng.normal(0, 1, 1000)
print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
Mean: -0.0944
Std: 1.0185
Min: -3.0476
Max: 2.9142
Q1: -0.7609
Q3: 0.5822


In [22]:
import pandas as pd
# Series dari list — index default 0,1,2...
s1 = pd.Series([85, 92, 78, 95, 88])

# Series dengan index kustom
nilai = pd.Series(
[85, 92, 78, 95],
index=['Alice','Bob','Caca','Dina']
)
print(nilai['Bob']) # → 92
print(nilai[nilai>80]) # filter
print(nilai.mean()) # → 87.5
print(nilai.describe()) # statistik lengkap

92
Alice    85
Bob      92
Dina     95
dtype: int64
87.5
count     4.000000
mean     87.500000
std       7.593857
min      78.000000
25%      83.250000
50%      88.500000
75%      92.750000
max      95.000000
dtype: float64


In [33]:
# Membuat DataFrame dari dictionary
data = {
'nama': ['Ali','Budi','Caca','Dina'],
'usia': [22, 25, 21, 23],
'kota': ['Jakarta','Bandung','Surabaya','Medan'],
'ipk': [3.8, 3.5, 3.9, 3.7]
}
df = pd.DataFrame(data)
# Informasi dasar
print(df.shape) # → (4, 4)
print(df.dtypes) # tipe data per kolom
print(df.columns) # nama-nama kolom

(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


In [44]:
import pandas as pd

# Memuat dari file lokal
df = pd.read_csv('customers-100.csv')

# Parameter penting (Disamakan menggunakan file 'customers-100.csv' agar tidak error)
df = pd.read_csv('customers-100.csv',
sep=',', # pemisah kolom (sesuaikan dengan file, contoh default ',')
encoding='utf-8', # encoding file
index_col='Index', # kolom sebagai index (sesuaikan nama kolom di filemu)
parse_dates=['Subscription Date'], # parse kolom tanggal (sesuaikan nama kolom di filemu)
na_values=['N/A','none'] # nilai kosong
)

# Eksplorasi standar setelah load
print(df.head()) # 5 baris pertama
print("\n--- Info Data ---")
df.info() # tipe data & missing
print("\n--- Deskripsi Data ---")
print(df.describe()) # statistik deskriptif






           Customer Id First Name Last Name                          Company  \
Index                                                                          
1      DD37Cf93aecA6Dc     Sheryl    Baxter                  Rasmussen Group   
2      1Ef7b82A4CAAD10    Preston    Lozano                      Vega-Gentry   
3      6F94879bDAfE5a6        Roy     Berry                    Murillo-Perry   
4      5Cef8BFA16c5e3c      Linda     Olsen  Dominguez, Mcmillan and Donovan   
5      053d585Ab6b3159     Joanna    Bender         Martin, Lang and Andrade   

                    City                     Country                 Phone 1  \
Index                                                                          
1           East Leonard                       Chile            229.077.5154   
2      East Jimmychester                    Djibouti              5153435776   
3          Isabelborough         Antigua and Barbuda         +1-539-402-0259   
4             Bensonview          Domin

In [46]:
import pandas as pd

# Contoh: Dataset Titanic (URL asli yang valid)
titanic_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(titanic_url)

# Filter satu kondisi
penumpang_selamat = df[df['Survived'] == 1]
penumpang_wanita = df[df['Sex'] == 'female']

# Filter kondisi ganda (& = AND, | = OR)
wanita_kelas1 = df[(df['Sex']=='female') & (df['Pclass']==1)]

# Seleksi kolom tertentu
df[['Name','Age','Sex','Survived']]

,Name,Age,Sex,Survived
0,"Braund, Mr. Owen Harris",22.0,male,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,1
2,"Heikkinen, Miss. Laina",26.0,female,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,1
4,"Allen, Mr. William Henry",35.0,male,0
...,...,...,...,...
886,"Montvila, Rev. Juozas",27.0,male,0
887,"Graham, Miss. Margaret Edith",19.0,female,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,female,0
889,"Behr, Mr. Karl Howell",26.0,male,1


In [47]:
# Pola dasar: groupby → aggregation
df.groupby('Pclass')['Survived'].mean()

# Agregasi multiple kolom & fungsi
hasil = df.groupby('Pclass').agg(
total = ('PassengerId', 'count'),
selamat = ('Survived', 'sum'),
pct_selamat= ('Survived', 'mean'),
rata_usia = ('Age', 'mean'),
max_fare = ('Fare', 'max')
)
hasil = hasil.round(3)
print(hasil)

# GroupBy multi-kolom
df.groupby(['Pclass','Sex'])['Survived']\
.mean().unstack().round(3)

        total  selamat  pct_selamat  rata_usia  max_fare
Pclass                                                  
1         216      136        0.630     38.233   512.329
2         184       87        0.473     29.878    73.500
3         491      119        0.242     25.141    69.550


Sex,female,male
Pclass,,
1,0.968,0.369
2,0.921,0.157
3,0.500,0.135
